[package]
name = "delegate"
description = "Method delegation with less boilerplate"
version = "0.1.0"
authors = ["Godfrey Chan <godfreykfc@gmail.com>"]
repository = "https://github.com/sfackler/rust-postgres-macros"
license = "MIT OR Apache-2.0"

[dependencies]
